/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    Catalogue: typeof import('./src/components/content/catalogue.vue')['default']
    Content: typeof import('./src/components/content/index.vue')['default']
    ContentCatalogue: typeof import('./src/components/content/catalogue.vue')['default']
    ContentContentScroll: typeof import('./src/components/content/contentScroll/index.vue')['default']
    ContentNavList: typeof import('./src/components/content/navList.vue')['default']
    ContentRecent: typeof import('./src/components/content/recent.vue')['default']
    ContentScroll: typeof import('./src/components/content/contentScroll/index.vue')['default']
    HeaderBlock: typeof import('./src/components/headerBlock.vue')['default']
    NavList: typeof import('./src/components/content/navList.vue')['default']
    Recent: typeof import('./src/components/content/recent.vue')['default']
  }
}
